### ISSUE TITLE
Breadchain governance page "Distribution Card" upgrade

### ISSUE THREAD

**Issue by diterra-code** [BreadchainCoop/crowdstaking-v2#123]
Two new UI changes for the ' amount to distribute' card on the governance/vote page of the Breadchain app:

[Figma Link](https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=2898-19710&t=4JW7K7uKpBPVKYFU-1)

- Smaller font size for the numbers after the "." 
<img width="430" alt="Screen Shot 2024-10-15 at 6 41 46 PM" src="https://github.com/user-attachments/assets/b6448b39-4d00-48c5-8116-d48ed29027ed">

- Adding the DAI savings rate to the 'Amount to distribute' card

<img width="420" alt="Screen Shot 2024-10-15 at 6 44 13 PM" src="https://github.com/user-attachments/assets/0012f038-08df-4f90-b2c5-35bdc6525f36">

Reach out if more clarity is needed!

**Comment by secbajor** [comment]
@subject026 a requirement of this ticket is to display the DAI savings rate.  To do so in real time, I found this `getYearlyRate` available from dai.js https://docs.makerdao.com/build/dai.js/savingsservice#getyearlyrate -- do you have any advice if this seems like a good approach, or am I missing anything already in the project that provides the rate?

**Comment by secbajor** [comment]
@diterra-code these changes are done - can you review on staging? https://deploy-preview-124--fanciful-lamington-ea5ee2.netlify.app/governance

**Comment by secbajor** [comment]
note the value for the current DSR used in this work was already available in the project to calculate the estimated yield. i wanted to find a way to confirm the value but am finding it hard to see where the rate is published. one place i found is [here](https://summer.fi/earn/dsr/0xa08bde17d0341d714DC15CC6d74cA5De12C03aF4#overview), but its a bit concerning to me because the DSR shown here does not match what i'm displaying in the application

**Comment by diterra-code** [comment]
> @diterra-code these changes are done - can you review on staging? https://deploy-preview-124--fanciful-lamington-ea5ee2.netlify.app/governance

@secbajor Looks great! 

Just two small details that cross my eyes:

1. I am realizing now that the numbers are smaller and look too close together. I propose adding a 6% spacing between the numbers.

2. It seems to me that the amount and the "Total accumulated yield" subtext are not center-aligned. Compared to the [Figma designs](https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=6729-165837&t=p1EdkBikqpgBk8Vn-1)?

Figma :

![image](https://github.com/user-attachments/assets/855900fe-b192-4fab-84f8-f1b995ffd0a7)


Netlify:

<img width="358" alt="Screen Shot 2024-10-26 at 10 02 55 PM" src="https://github.com/user-attachments/assets/6c06f36c-68ad-4bcb-95b9-f6b7fee7473e">

**Comment by diterra-code** [comment]
> note the value for the current DSR used in this work was already available in the project to calculate the estimated yield. i wanted to find a way to confirm the value but am finding it hard to see where the rate is published. one place i found is [here](https://summer.fi/earn/dsr/0xa08bde17d0341d714DC15CC6d74cA5De12C03aF4#overview), but its a bit concerning to me because the DSR shown here does not match what i'm displaying in the application

On this, I would be best to ask lewis or josh on best source for DSR.

**Comment by secbajor** [comment]
@diterra-code thanks -- made those adjustments to character spacing and center alignment. i also noticed the bread icon needed a slight adjustment, made that change as well. 

can you confirm again on https://deploy-preview-124--fanciful-lamington-ea5ee2.netlify.app/governance ?

**Comment by diterra-code** [comment]
> @diterra-code thanks -- made those adjustments to character spacing and center alignment. i also noticed the bread icon needed a slight adjustment, made that change as well.
> 
> can you confirm again on https://deploy-preview-124--fanciful-lamington-ea5ee2.netlify.app/governance ?

Looks perfect!

**Comment by secbajor** [comment]
This was deployed to prod; closing.
