### ISSUE TITLE
Governance / Vote page - New UX/UI design improvements & upgrades

### ISSUE THREAD

**Issue by diterra-code** [BreadchainCoop/crowdstaking-v2#125]
Here are the new design upgrade and changes for the Governance/ Vote page:

# 1. Update title text from "Voting Power" to " My voting power":

**Figma Link:**
https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=2903-20282&t=BRFj0zxHBSRN2rrY-1

**Screen shot:**

![image](https://github.com/user-attachments/assets/bf04835f-44a4-44c9-adba-3ac18022a9a3)

# 2. Update project profile image of CCA (Crypto Commons Association)

**Figma Link:**
https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=6729-159070&t=BRFj0zxHBSRN2rrY-1

**Screen shot:**
![image](https://github.com/user-attachments/assets/bb6bba59-be75-4e70-b2b5-12b76013a6be)

# 3. New project card design (Web & Mobile)

- Bold title
- Project BREAD holdings & Voting power information chips
- New voting calculator design

**Figma Link Dark web:**

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=6729-166081&t=BRFj0zxHBSRN2rrY-1

**Figma Link Light web:**

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=6729-160472&t=BRFj0zxHBSRN2rrY-1

**Figma Link Dark mobile:**

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=6729-165727&t=BRFj0zxHBSRN2rrY-1

**Figma Link Light mobile:**

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=6729-159784&t=BRFj0zxHBSRN2rrY-1

**Screen shot:**

![image](https://github.com/user-attachments/assets/02490621-55db-4e74-a677-7bad32720630)

![image](https://github.com/user-attachments/assets/11d5b615-d095-410f-9296-bf4464d5814d)

**Comment by diterra-code** [comment]
@secbajor After reviewing the development work on https://deploy-preview-126--endearing-biscuit-e5a874.netlify.app/governance

I have the following project card UI feedback:

- The project card title should be 'bold'
- I want to try the spacing between the title and the info chips. It was 4 px and now I want to try 8px as it seems too close to each other.
- Info chip padding 

## Project titles

The project titles on the current designs on Netlify app should be made bold.

The project title should be font-weight (bold) : 

**Figma design:**

![image](https://github.com/user-attachments/assets/d808c59c-72b3-48f4-97eb-0170cc0d3ff8)


**Current development displayed as:**
<img width="299" alt="Screen Shot 2024-11-11 at 2 04 02 PM" src="https://github.com/user-attachments/assets/a11965a0-1ebb-4e3f-a10e-ba6d62416dd2">

## Title and Chips vertical spacing

The spacing (4px) between the title and info chips seems to be to small to me.

Screenshot:
<img width="337" alt="Screen Shot 2024-11-11 at 2 17 02 PM" src="https://github.com/user-attachments/assets/24f14b8a-6113-4932-a1b7-1e9f2764bd87">

I suggest making it **8px** to allow the components to breathe;

As in the figma designs:

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=6715-48846&t=fwgm496aBfALcgSz-1





## Info chip padding

![image](https://github.com/user-attachments/assets/3c24cb75-8156-4c38-8d77-219c711f5c29)

the layout is as follows:


<img width="297" alt="Screen Shot 2024-11-11 at 1 57 54 PM" src="https://github.com/user-attachments/assets/2c9c6ca9-ad7b-42cc-8292-7148c92161fe">

width: Hug (123px)px;
height: Hug (32px)px;
padding: 4px **6px** 4px 4px;
gap: 8px;
border-radius: 16px 0px 0px 0px;
border: 1px 0px 0px 0px;
opacity: 0px;

Important to note:

The right padding is 6px instead of 4 px . This is especially for the external icon. I am curious to know how the info chips will look like using this padding format.

Everything else looks good!

await the new version,

**Comment by secbajor** [comment]
@diterra-code made those updates!
- project title bold
- increased spacing between project title / badges
- adjusted padding of badges
- added hover state for badges with link

https://deploy-preview-126--endearing-biscuit-e5a874.netlify.app/governance

**Comment by diterra-code** [comment]
Looks really good, just wondering why one treasury is without a treasury link (symbiota).

Some other quick remarks I discovered in the UI:

## The learn more card is super stretched:

<img width="1049" alt="Screen Shot 2024-11-11 at 6 56 13 PM" src="https://github.com/user-attachments/assets/7bec2119-25bf-469e-8d0a-775bc9654475">

I suggest to make the card a fixed height of 200 px as in the Figma:

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=6729-165837&t=naNW9OwLz8qh8qaU-1

## Make Bread holdings with two decimals behind the comma

Currently, the total Bread held is rounded up. I suggest to add two decimals behind the comma of each projects bread holding. Reason is, it will look more similar to how the majority of the world displays a currency.

**I also increased the number spacing for all chips to 2%** could this be adjusted aswell?

Current:
<img width="119" alt="Screen Shot 2024-11-11 at 7 10 15 PM" src="https://github.com/user-attachments/assets/66f83f83-6d09-48f8-b0bc-34656c0e9c7a">


Suggestion:

![image](https://github.com/user-attachments/assets/c3356b37-8622-4c40-b0ac-2bde2f314ca5)

### Last question

I was just wondering if the project image and title & chips are center aligned.

**Comment by secbajor** [comment]
@diterra-code latest has the following changes https://deploy-preview-126--endearing-biscuit-e5a874.netlify.app/governance

- learn more card set to 200px height
- added decimal places for bread holding
- increased letter spacing on chips
- when a project has 0 bread (symbiota) it will now display "0.00"

> I was just wondering if the project image and title & chips are center aligned.

no, i think they are not center aligned

**Comment by secbajor** [comment]
@diterra-code 
> I was just wondering if the project image and title & chips are center aligned.

oh actually do you mean vertically or horizontally? they have a center alignment set, but obviously not set to centered horizontally within that space...

**Comment by diterra-code** [comment]
It all looks perfect!

One last design request:

All hover state of components of the project card for 'light' mode should be a darker shade of pink:

Currently its: #E873D3

Needs to be: #E873D3

**Note:** This is only for the light version due to contrast reasons.

After this update I feel confident to say its deploy ready @secbajor

**Comment by diterra-code** [comment]
I have a few questions about spacing.

Is the spacing within the info chips between the **icons** and the **text** fixed at 8px?

<img width="233" alt="Screen Shot 2024-11-12 at 4 50 32 PM" src="https://github.com/user-attachments/assets/3b8b6604-76e3-4bf3-80f6-89d28802accf">

The reason is, they look quite spaced apart and I was wondering if they are 8px. And if so we might have to reduce the spacing to 6px.

As the design might look and feel different in development.

**Comment by diterra-code** [comment]
> @diterra-code
> 
> > I was just wondering if the project image and title & chips are center aligned.
> 
> oh actually do you mean vertically or horizontally? they have a center alignment set, but obviously not set to centered horizontally within that space...

Yes I mean align the vertical centers:
<img width="32" alt="Screen Shot 2024-11-12 at 4 53 58 PM" src="https://github.com/user-attachments/assets/c21b1e0f-f973-4b11-9b40-fa671bae9ca5">

**Comment by secbajor** [comment]
@diterra-code thanks for your detailed feedback -- i changed the light theme color to your suggested shade of pink and also fixed the spacing which was i found was 12px - reduced it to 8px as suggested 

ill go ahead and move this forward now :)

**Comment by secbajor** [comment]
Deployed to production.
