### ISSUE TITLE
Bake page: Bridge module design

### ISSUE THREAD

**Issue by secbajor** [BreadchainCoop/crowdstaking-v2#143]
This is a UX/UI feature for the Bake page of app.breadchain.xyz

**Reason:** Provide non-Gnosis Chain users a quick link to bridge assets from other networks to gnosis.

Bridge to link [Jumper exchange](https://jumper.exchange/?fromChain=100&toChain=100&toToken=0x0000000000000000000000000000000000000000)

**Screenshot:**
![Image](https://github.com/user-attachments/assets/afd40118-a27c-4c26-86b3-dfc6719cdd33)

**Figma link (Dark):**
https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=7078-54088&t=16049lI78qMRBMmY-1

**Screenshot light:**

![Image](https://github.com/user-attachments/assets/69611f33-9451-4700-ab32-2de637b4c554)

**Figma link (light):**

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=7097-54351&t=16049lI78qMRBMmY-1

**Bridge Button card URL:**
https://jumper.exchange/?fromChain=100&toChain=100&toToken=0x0000000000000000000000000000000000000000

## Bridge card mobile version

![Image](https://github.com/user-attachments/assets/d4a07217-a529-4ecb-ba90-7d26fc050f86)

Figma link Dark:

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=7164-6061&t=pVbzOBnG7ILXShPS-1

Figma link Light: 

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=7164-6096&t=pVbzOBnG7ILXShPS-1

**Animation:** there is a hover state, with an easing in transition.

**Comment by secbajor** [comment]
@diterra-code preview available here! please take a look and provide me any feedback :) 

https://deploy-preview-154--fanciful-lamington-ea5ee2.netlify.app/

**Comment by diterra-code** [comment]
@secbajor just took a look! looks amazing. two small interaction comments I wanted to highlight;

- In the hover state, the arrow slightly moves to the right in the Figma prototype, and I think you can also see this in the second stage of the design. 

- The last question is, is it possible for the hover state to fade in slower or more gentle?

Once these changes are made it is ready to deploy.

**Comment by secbajor** [comment]
@diterra-code good catch -- here's the latest with those updates! https://deploy-preview-154--fanciful-lamington-ea5ee2.netlify.app/

**Comment by diterra-code** [comment]
Hi @secbajor  looks really good, just one question, is the hover state in light mode using this color hex: #D04EC5  for the border and arrow icon? 

If this is the case then its good, if not then could you change it?

**Comment by RonTuretzky** [comment]
🎉🎉🎉
