### ISSUE TITLE
Bake page: UX & UI upgrade: make Bake and Burn visable tabs

### ISSUE THREAD

**Issue by secbajor** [BreadchainCoop/crowdstaking-v2#149]
## Description/ Reason:

After showcasing the Breadchain app to a non-crypto user, It became apparent that finding the burn or bake tab was difficult. 

Currently, the Bake/Burn tab is changed by clicking the center arrow. This becomes difficult for people who have never used a DEX before.  Therefore, I suggest to create an additional tab at the top of the bake/burn module. This will make it clear that this module has two different tabs and these will also be properly named.

### IMPORTANT detail:

New vertical padding for the whole bake/burn module card:

- Old Vertical padding: 5px
- New vertical padding: 10px

**Screenshot:**

![Image](https://github.com/user-attachments/assets/94eca5ba-a4ba-4d0f-8e5d-c25bb83fde2d)

**Figma Link Module:**
https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=2140-975&t=pVbzOBnG7ILXShPS-1

 ## Tab buttons & states:

**screenshot:**

![Image](https://github.com/user-attachments/assets/dc305b1b-9cdd-4285-99b0-1fe3ff6f81ed)

States:
![Image](https://github.com/user-attachments/assets/10b7bf56-4243-4e36-8eda-99f67a9318c4)

**Figma link:**

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=7165-53455&t=pVbzOBnG7ILXShPS-1

##Light mode

Figma link:

https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=7165-54132&t=pVbzOBnG7ILXShPS-1

**Comment by secbajor** [comment]
@diterra-code this is posted for review here https://deploy-preview-158--fanciful-lamington-ea5ee2.netlify.app/ !

**Comment by diterra-code** [comment]
@secbajor It is looking good! I wanted to review the horizontal and vertical padding of all button states.

- Check the padding should be 16px and 8px
- The hover state lacks the background color #DE56E7 with a 10 percent opacity.

**Comment by diterra-code** [comment]
@secbajor Just did a second review of the new changes.

I was wondering if the spacing between the tabs is 8 px and if so maybe we should make it 4 px. As they seem quite far apart on my screen.

Let me know how it looks with these changes.

**Comment by secbajor** [comment]
@diterra-code no you have it right, i had it set to 12px. so ive just decreased it to 8px as specified. i need to work on my brain's px to rem conversions 🤪 

updated https://deploy-preview-158--fanciful-lamington-ea5ee2.netlify.app/

**Comment by diterra-code** [comment]
Perfect! no more comments. It is ready for deployment in my opinion.

**Comment by secbajor** [comment]
deployed to prod
