### ISSUE TITLE
LP Vaults: Number formatting

### ISSUE THREAD

**Issue by secbajor** [BreadchainCoop/crowdstaking-v2#150]
Format voting power numbers throughout the new screens for LP Locking feature
- Format voting power display number, preserve decimal places when value is 0 (display as 0.00) 
- Format number in unlocking lp token popup
- Review other numbers and ensure proper formatting

**Comment by secbajor** [comment]
@diterra-code this ticket is about number formatting for LP feature -- can you clarify for us -- should Voting Power be displayed with two decimal places (1500.11) or only as a whole number (1500) ?

**Comment by diterra-code** [comment]
@secbajor lets keep it at two decimals for now.

**Comment by secbajor** [comment]
@diterra-code then do all the numbers look good here in the "My Voting Power" panel? in terms of how many decimal places and their formatting? 

![Image](https://github.com/user-attachments/assets/4bc344f0-6af0-463b-b0c8-058220a212b9)

**Comment by diterra-code** [comment]
@secbajor After reviewing the designs and the current way voting power is displayed I think one decimal would be better to display.

I am wondering when you would want me to come in and review the current UI to see if the designs match. As I spot a few inconsistencies with the current UI

**Comment by secbajor** [comment]
@diterra-code ok - here's what I have with that change from 2 decimals to 1 

![Image](https://github.com/user-attachments/assets/c6b8fddf-a617-44ac-808b-7dcd5cab8755)

you're welcome to provide feedback, im just hesitant to ask for it because there are a few PR's opened but not merged that include layout and UI fixes. so you may be providing feedback on things we already have resolved. i'm planning to have them all merged by Monday so you can review the latest

**Comment by diterra-code** [comment]
@secbajor Looks good!

**Comment by secbajor** [comment]
merged to development; closing.
