### ISSUE TITLE
LP Vaults: Account for project wallets receiving VP from locked LP tokens

### ISSUE THREAD

**Issue by subject026** [BreadchainCoop/crowdstaking-v2#155]
"this is raising the question for me whether project wallets could also have locked LP tokens, and if so, my understanding is their voting power will similarly need to consider both their bread holding and LP tokens. 

what do you think about having this VotingPowerContext return voting power for a passed in wallet address, since now it can only fetch voting power for the logged in user? my thinking is this would make it more flexible and centralize the logic of calculating voting power."

_Originally posted by @secbajor in https://github.com/BreadchainCoop/crowdstaking-v2/pull/141#discussion_r1857252545_

**Comment by secbajor** [comment]
i took a closer look at this and have convinced myself it's fine the way it is -- for the projects the voting power is fetched from getCurrentVotingPower which returns a total from both bread holding and lp tokens 👍🏼

there is maybe still a future opportunity to make the contexts reusable for the user and the projects, but is not necessary work for now. 

closing!
