### ISSUE TITLE
Vote page: Update project card profile to higher quality images

### ISSUE THREAD

**Issue by secbajor** [BreadchainCoop/crowdstaking-v2#197]
Here are the new images of the following project cards:

### Breadchain core:

![Image](https://github.com/user-attachments/assets/fb63837e-1d1a-4d09-b284-3129ad7c7bb5)

### Breadchain Shared treasury:

![Image](https://github.com/user-attachments/assets/7b9c2bf7-d7de-4a91-9882-844003f1be38)

### Symbiota:

![Image](https://github.com/user-attachments/assets/f36d430f-28db-46dc-a066-d56e3b05614d)

### LaborDAO:

![Image](https://github.com/user-attachments/assets/99197ee4-bded-4724-968b-dae1b03ffc8d)

### Citizenwallet:

![Image](https://github.com/user-attachments/assets/7d10b8b4-4942-4015-8f8f-ccb6d1c6d877)

**Comment by secbajor** [comment]
@diterra-code can you update this ticket to include logo, name, and short description for the new project card to be added ?

**Comment by diterra-code** [comment]
For ReFi DAO?

I think i opened a ticket /draft on this one.

**Comment by secbajor** [comment]
ah got it, thanks @diterra-code !

**Comment by secbajor** [comment]
updated images on prod; closing
