### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by subject026** [BreadchainCoop/crowdstaking-v2#57]
Mockup:
![Screenshot 2024-10-10 at 9 57 52 AM](https://github.com/user-attachments/assets/afd1ab73-9c9c-4067-990e-749e6d9c1476)
https://www.figma.com/design/2sWRCrux6a47zBXTwDVJxh/Breadchain-crowdstake?node-id=505-8&node-type=canvas

Existing page looks like:
![image](https://github.com/BreadchainCoop/crowdstaking-v2/assets/36077932/6582619c-c084-4d39-b5b6-90d2b379981c)

**Comment by secbajor** [comment]
This was deployed to prod; closing.
